CREATE TABLE IF NOT EXISTS raw_events (
  event_id String,
  schema_version UInt16,
  sdk_name LowCardinality(String),
  sdk_version LowCardinality(String),
  project_id UUID,
  app_id String,
  env LowCardinality(String),
  release String,
  event LowCardinality(String),
  timestamp DateTime64(3, 'UTC'),
  received_at DateTime64(3, 'UTC'),
  page_url String,
  page_route String,
  user_id Nullable(String),
  dept_id Nullable(String),
  role_id Nullable(String),
  session_id String,
  device_id String,
  page_view_id String,
  ua String,
  os LowCardinality(String),
  browser LowCardinality(String),
  payload_json String,
  feature_id Nullable(UUID),
  feature_key Nullable(String),
  feature_stage LowCardinality(Nullable(String)),
  operation_instance_id Nullable(String),
  interaction_type LowCardinality(Nullable(String)),
  workflow_instance_id Nullable(String),
  workflow_key Nullable(String),
  workflow_definition_version Nullable(UInt32),
  workflow_step_key Nullable(String),
  workflow_step_order Nullable(UInt32),
  lifecycle_phase LowCardinality(Nullable(String)),
  viewport_bucket LowCardinality(Nullable(String)),
  error_category LowCardinality(Nullable(String)),
  error_type LowCardinality(Nullable(String)),
  error_name Nullable(String),
  error_message Nullable(String),
  error_stack_frame Nullable(String),
  error_group_id Nullable(String),
  request_method LowCardinality(Nullable(String)),
  request_path Nullable(String),
  http_status Nullable(UInt16),
  resource_type LowCardinality(Nullable(String)),
  vital_name LowCardinality(Nullable(String)),
  vital_value Nullable(Float64),
  vital_rating LowCardinality(Nullable(String)),
  navigation_type LowCardinality(Nullable(String)),
  duration_ms Nullable(UInt64),
  visible_duration_ms Nullable(UInt64),
  request_id UUID,
  origin String,
  INDEX idx_feature_key feature_key TYPE bloom_filter(0.01) GRANULARITY 4,
  INDEX idx_session_id session_id TYPE bloom_filter(0.01) GRANULARITY 4,
  INDEX idx_workflow_instance workflow_instance_id TYPE bloom_filter(0.01) GRANULARITY 4,
  INDEX idx_error_group error_group_id TYPE bloom_filter(0.01) GRANULARITY 4,
  INDEX idx_release release TYPE bloom_filter(0.01) GRANULARITY 4
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(received_at)
ORDER BY (app_id, env, toDate(received_at), event, page_route, timestamp, event_id)
TTL received_at + INTERVAL 90 DAY DELETE
SETTINGS index_granularity = 8192;
