CREATE TABLE IF NOT EXISTS project_collector_settings (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  project_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  version INT UNSIGNED NOT NULL,
  api_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  api_sample_rate DECIMAL(6, 5) NOT NULL DEFAULT 1,
  api_slow_threshold_ms INT UNSIGNED NOT NULL DEFAULT 2000,
  api_global_fetch BOOLEAN NOT NULL DEFAULT FALSE,
  resources_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  resources_sample_rate DECIMAL(6, 5) NOT NULL DEFAULT 1,
  first_screen_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  first_screen_sample_rate DECIMAL(6, 5) NOT NULL DEFAULT 1,
  list_render_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  list_render_sample_rate DECIMAL(6, 5) NOT NULL DEFAULT 1,
  long_tasks_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  long_tasks_sample_rate DECIMAL(6, 5) NOT NULL DEFAULT 1,
  blank_screen_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  blank_screen_sample_rate DECIMAL(6, 5) NOT NULL DEFAULT 1,
  breadcrumbs_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  breadcrumbs_sample_rate DECIMAL(6, 5) NOT NULL DEFAULT 1,
  breadcrumb_action_keys JSON NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  effective_from TIMESTAMP(3) NOT NULL,
  effective_to TIMESTAMP(3) NULL,
  created_by_user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_project_collector_settings_version (project_id, version),
  KEY idx_project_collector_settings_effective (project_id, status, effective_from),
  CONSTRAINT chk_project_collector_settings_status CHECK (status IN ('active', 'superseded')),
  CONSTRAINT chk_project_collector_settings_api_rate CHECK (api_sample_rate BETWEEN 0 AND 1),
  CONSTRAINT chk_project_collector_settings_resource_rate CHECK (resources_sample_rate BETWEEN 0 AND 1),
  CONSTRAINT chk_project_collector_settings_first_screen_rate CHECK (first_screen_sample_rate BETWEEN 0 AND 1),
  CONSTRAINT chk_project_collector_settings_list_rate CHECK (list_render_sample_rate BETWEEN 0 AND 1),
  CONSTRAINT chk_project_collector_settings_long_task_rate CHECK (long_tasks_sample_rate BETWEEN 0 AND 1),
  CONSTRAINT chk_project_collector_settings_blank_rate CHECK (blank_screen_sample_rate BETWEEN 0 AND 1),
  CONSTRAINT chk_project_collector_settings_breadcrumb_rate CHECK (breadcrumbs_sample_rate BETWEEN 0 AND 1),
  CONSTRAINT chk_project_collector_settings_slow_threshold CHECK (api_slow_threshold_ms BETWEEN 1 AND 60000),
  CONSTRAINT fk_project_collector_settings_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE RESTRICT,
  CONSTRAINT fk_project_collector_settings_user FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
